### ISSUE TITLE
addPlayTime при добавлении времени для игрока не проверяет была ли у данного игрока установлена игра

### ISSUE THREAD

**Issue by Toybear1986** [KlimovaTE/TeamProject#11]
# Описание
addPlayTime при добавлении времени для игрока не проверяет была ли у данного игрока установлена игра.
Поскольку в описании метода нет требования на такую проверку, регистрирую данную проблему как `enhancement`.

# Локация
https://github.com/KlimovaTE/TeamProject/blob/e2bc5ce76a9995e90486810ec40053d034a575c9/src/main/java/ru/netology/GameStore.java#L41-L52

# Шаги воспроизведения
1. Открыть [проект](https://github.com/KlimovaTE/TeamProject) в IDEA
2. Получить актуальный список тестов из ветки `gamestore` 
3. В классе `GameStoreTest` запустить тест `shouldAddPlaytimeForNewPlayer`

*Ожидаемый результат:* Время игры не должно записываться для игрока у которого игра не была установлена
*Фактический результат:* Время игры записано для игрока у которого игра не была установлена

# Скриншот
![image](https://user-images.githubusercontent.com/50303627/188624661-da438152-5686-4807-84fc-45c43ea77cce.png)

# Окружение
* **Операционная система:** Windows 11 Pro Версия 21H2 Сборка ОС 22000.856
* **IDE:** IntelliJ IDEA 2022.2 (Community Edition) Build #IC-222.3345.118, built on July 26, 2022
* **Java:**  corretto-11.0.16

**Comment by KlimovaTE** [comment]
Если добавить проверку в addPlayTime в классе GameStore и выкидывать исключение, в классе Player метод play никогда не дойдет до выкидывания исключения RuntimeException. А это требуется по условию задачи. Возможно, надо исправить метод play, чтобы метод addPlayTime вызывался только после проверки установки игры (в методе play это как раз и делается).

**Comment by Toybear1986** [comment]
Предлагаю вечером обсудить, потому как я не согласен с данным утверждением. Потому что install вносит запись что игрок проиграл 0 часов. Т.е. ключ Игрок добавляется со значением 0. Таким образом при проверке в методе Play все отрабатывает как положено. Ну и install используют метод pu, а не addPlayTime, поэтому они вообще никак не связаны. В общем я не понимаю, что именно тебя смущает, потому что строчка game.getStore().addPlayTime(name, hours); просто получает имя и часы, а дальше проверяются условия и если они выполнены, возвращается добавленное время, а если они не выполнены, возвращается исключение. К слову, все текущие тесты в Playertest, проходят и без этой строчки, поэтому она в сущности ни на что не влияет. Даже не знаю зачем она там)
