### ISSUE TITLE
Метод sumGenre в классе Player неправильно считает суммарное время игры в игры заданного жанра, если игрок поиграл в две игры этого жанра.

### ISSUE THREAD

**Issue by KlimovaTE** [KlimovaTE/TeamProject#12]
# Описание
Метод sumGenre в классе Player неправильно считает суммарное время игры в игры заданного жанра, если игрок поиграл в две игры этого жанра.

# Локация дефекта
https://github.com/KlimovaTE/TeamProject/blob/d481bc0fab9d6aaf03e6e186cb1dc73c069cd770/src/main/java/ru/netology/Player.java#L45-L55
https://github.com/KlimovaTE/TeamProject/blob/d481bc0fab9d6aaf03e6e186cb1dc73c069cd770/src/main/java/ru/netology/Player.java#L50-L52

# Шаги воспроизведения
1. Открыть [проект](https://github.com/KlimovaTE/TeamProject/issues/new) как Maven проект в IDEA
2. В классе PlayerTest запустить тест shouldSumGenreIfTwoGameTwicePlay with Coverage.
3. Тест провален.

*Ожидаемый результат:* Метод возвращает суммарное количество часов, проигранное во все игры этого жанра этим игроком
*Фактический результат:* Метод возвращает ошибочное количество часов, проигранное во все игры этого жанра этим игроком

# Скриншот
![image](https://user-images.githubusercontent.com/106732340/188852437-cd83bb80-f4f1-4344-b4e6-523fff1c5861.png)
# Окружение
* **Операционная система:** Windows 10 Pro х64
* **IDE** IntelliJ IDEA 2022.1.3 (Community Edition)
* **JAVA** OpenJDK 11

**Comment by Toybear1986** [comment]
Да, ты права, уже нашел в чем ошибка, воспроизводилось не каждый раз по той простой причине, что был важен именно порядок перебора элементов коллекции, по сути если сначала игрок сыграл в игру искомого жанра, эти данные записываются, однако при следующей проверке они выставляются снова в ноль. Правка в один символ) Сделаю после того, как ты закончишь свои репорты
