### ISSUE TITLE
Метод mostPlayerByGenre в классе Player не возвращает игру заданного жанра, в которую играли больше всего

### ISSUE THREAD

**Issue by KlimovaTE** [KlimovaTE/TeamProject#13]
# Описание
Метод mostPlayerByGenre в классе Player не возвращает игру заданного жанра, в которую играли больше всего.

# Локация дефекта
(https://github.com/KlimovaTE/TeamProject/blob/5ce2faa30c5bdfa2e6eb47d96e808264a816a378/src/main/java/ru/netology/Player.java#L71-L86)

# Шаги воспроизведения
1. Открыть [проект](https://github.com/KlimovaTE/TeamProject/issues/new) как Maven проект в IDEA
2. В классе PlayerTest запустить тест shouldMostPlayerByGenreIfTwo with Coverage.
3. Тест провален.

*Ожидаемый результат:* Метод возвращает игру заданного жанра, в которую играли больше всего.
*Фактический результат:* Метод возвращает null.

# Скриншот
![image](https://user-images.githubusercontent.com/106732340/188874815-88bf5429-3cc2-4c63-b467-acbe3fb0577b.png)
# Окружение
* **Операционная система:** Windows 10 Pro х64
* **IDE** IntelliJ IDEA 2022.1.3 (Community Edition)
* **JAVA** OpenJDK 11

**Comment by Toybear1986** [comment]
Скорее всего связана с #12. Я посмотрю)

**Comment by Toybear1986** [comment]
@KlimovaTE по сути, здесь ситуация такая же, как в https://github.com/KlimovaTE/TeamProject/issues/9 потому что под условия подходит две игры и все зависит от порядка перебора
