### ISSUE TITLE
Метод play в классе Player не добавляет проигранное количество часов в мапу игрока

### ISSUE THREAD

**Issue by KlimovaTE** [KlimovaTE/TeamProject#5]
# Описание
Метод play в классе Player не добавляет проигранное количество часов в мапу игрока.

# Локация дефекта
https://github.com/KlimovaTE/TeamProject/blob/d481bc0fab9d6aaf03e6e186cb1dc73c069cd770/src/main/java/ru/netology/Player.java#L33-L41
https://github.com/KlimovaTE/TeamProject/blob/d481bc0fab9d6aaf03e6e186cb1dc73c069cd770/src/main/java/ru/netology/Player.java#L36

# Шаги воспроизведения
1. Открыть [проект](https://github.com/KlimovaTE/TeamProject/issues/new) как Maven проект в IDEA
2. В классе PlayerTest запустить тест shouldSumGenreIfOneGame.
3. Тест провален.

*Ожидаемый результат:* Проигранное игроком количество часов добавляется в мапу игрока
*Фактический результат:* Метод play не добавляет проигранное количество часов в мапу игрока

# Скриншот
![image](https://user-images.githubusercontent.com/106732340/188331927-9366ea28-7f62-469c-a9dd-1dc28784ccc8.png)
# Окружение
* **Операционная система:** Windows 10 Pro х64
* **IDE** IntelliJ IDEA 2022.1.3 (Community Edition)
* **JAVA** OpenJDK 11

**Comment by Toybear1986** [comment]
@KlimovaTE исправил
