### ISSUE TITLE
Метод play в классе Player не выкидывает RuntimeException, если принимает в качестве параметра игру, которая не была установлена

### ISSUE THREAD

**Issue by KlimovaTE** [KlimovaTE/TeamProject#6]
# Описание
Метод play не выкидывает RuntimeException, если принимает в качестве параметра игру, которая не была установлена.
# Локация дефекта
https://github.com/KlimovaTE/TeamProject/blob/d481bc0fab9d6aaf03e6e186cb1dc73c069cd770/src/main/java/ru/netology/Player.java#L33-L41
https://github.com/KlimovaTE/TeamProject/blob/d481bc0fab9d6aaf03e6e186cb1dc73c069cd770/src/main/java/ru/netology/Player.java#L36

# Шаги воспроизведения
1. Открыть [проект](https://github.com/KlimovaTE/TeamProject/issues/new) как Maven проект в IDEA
2. В классе PlayerTest запустить тест shouldPlayIfGameNotInstalled.
3. Тест провален.

*Ожидаемый результат:* Метод play выкидывает сообщение RuntimeException, если принимает в качестве параметра игру, которая не была установлена.
*Фактический результат:* Метод play не выкидывает сообщение RuntimeException, если принимает в качестве параметра игру, которая не была установлена.

# Скриншот
![image](https://user-images.githubusercontent.com/106732340/188370267-0e9ede43-993e-4e7d-9a9b-77eaead3117c.png)
# Окружение
* **Операционная система:** Windows 10 Pro х64
* **IDE** IntelliJ IDEA 2022.1.3 (Community Edition)
* **JAVA** OpenJDK 11

**Comment by Toybear1986** [comment]
@KlimovaTE проправил, проверил
