### ISSUE TITLE
Метод mostPlayerByGenre в классе Player всегда возвращает null

### ISSUE THREAD

**Issue by KlimovaTE** [KlimovaTE/TeamProject#7]
# Описание
Метод mostPlayerByGenre в классе Player всегда возвращает null.
# Локация дефекта
https://github.com/KlimovaTE/TeamProject/blob/d481bc0fab9d6aaf03e6e186cb1dc73c069cd770/src/main/java/ru/netology/Player.java#L59-L61

# Шаги воспроизведения
1. Открыть [проект](https://github.com/KlimovaTE/TeamProject/issues/new) как Maven проект в IDEA
2. В классе PlayerTest запустить тест shouldMostPlayerByGenre.
3. Тест провален.

*Ожидаемый результат:* Метод mostPlayerByGenre возвращает игру запрошенного жанра, в которую играли больше всего
*Фактический результат:* Метод mostPlayerByGenre всегда возвращает null

# Скриншот
![image](https://user-images.githubusercontent.com/106732340/188374669-074faebc-2bd0-4cf6-9377-f19e1d4a4938.png)
# Окружение
* **Операционная система:** Windows 10 Pro х64
* **IDE** IntelliJ IDEA 2022.1.3 (Community Edition)
* **JAVA** OpenJDK 11

**Comment by Toybear1986** [comment]
@KlimovaTE Код исправил, однако, предлагаемый тест подходит только для проверки случая если в игру не играли, таким образом ожидаемый результат в тест не правильный. Кроме того нужен еще тест если в игру уже поиграли, для увеличения тестового покрытия.

**Comment by Toybear1986** [comment]
@KlimovaTE ты оба тестовых случая покрыла? Если играл и если не играли? Вижу, что правку ты сделала только для случае если поиграли
